baseURL = "/"
languageCode = "en-us"
title = "Tappr"
theme = "kube"
description = "Tappr is a payments company uniting the worlds payments under a single, easily accessible payments platform"
Paginate = 4
enableInlineShortcodes = true
[Params]
  RSSLink = "/index.xml"
  author = "Tappr" # add your company name
  github = "Tappr"
  twitter = "" # add your twitter profile

[[menu.main]]
    name = "Docs"
    weight = -100
    url = "/docs/"
